<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['QFGW'] => 'QFGW',
        IUserGroup::ID['QWWXB'] => 'QWWXB',
        IUserGroup::ID['RMTZX'] => 'RMTZX',
        IUserGroup::ID['SWJ'] => 'SWJ',
        IUserGroup::ID['ZJW'] => 'ZJW',
        IUserGroup::ID['WJW'] => 'WJW',
        IUserGroup::ID['NW'] => 'NW',
        IUserGroup::ID['GZW'] => 'GZW',
        IUserGroup::ID['KJJ'] => 'KJJ',
        IUserGroup::ID['GXJ'] => 'GXJ',
        IUserGroup::ID['GAFJ'] => 'GAFJ',
        IUserGroup::ID['JCY'] => 'JCY',
        IUserGroup::ID['FY'] => 'FY',
        IUserGroup::ID['CZJ'] => 'CZJ',
        IUserGroup::ID['SHUIWJ'] => 'SHUIWJ',
        IUserGroup::ID['WLJ'] => 'WLJ',
        IUserGroup::ID['JRJ'] => 'JRJ',
        IUserGroup::ID['SCJGJ'] => 'SCJGJ',
        IUserGroup::ID['RSJ'] => 'RSJ',
        IUserGroup::ID['MZJ'] => 'MZJ',
        IUserGroup::ID['YGJ'] => 'YGJ',
        IUserGroup::ID['YJGLJ'] => 'YJGLJ',
        IUserGroup::ID['JYJ'] => 'JYJ',
        IUserGroup::ID['SFJ'] => 'SFJ',
        IUserGroup::ID['ZFB'] => 'ZFB',
        IUserGroup::ID['QWXCB'] => 'QWXCB',
        IUserGroup::ID['XFBCZD'] => 'XFBCZD',
        IUserGroup::ID['BCZ'] => 'BCZ',
        IUserGroup::ID['YXFZ'] => 'YXFZ',
        IUserGroup::ID['XDZ'] => 'XDZ',
        IUserGroup::ID['DZZZ'] => 'DZZZ',
        IUserGroup::ID['SKZ'] => 'SKZ',
        IUserGroup::ID['XTTZ'] => 'XTTZ',
        IUserGroup::ID['QGHZRZYJ'] => 'QGHZRZYJ',
        IUserGroup::ID['STHJJ'] => 'STHJJ',
        IUserGroup::ID['TJJ'] => 'TJJ',
        IUserGroup::ID['DAJ'] => 'DAJ',
        IUserGroup::ID['RFB'] => 'RFB',
        IUserGroup::ID['CGW'] => 'CGW',
        IUserGroup::ID['BMJ'] => 'BMJ',
        IUserGroup::ID['QSWJ'] => 'QSWJ',
        IUserGroup::ID['QWTZB'] => 'QWTZB',
        IUserGroup::ID['XCJ'] => 'XCJ',
        IUserGroup::ID['PDJ'] => 'PDJ',
        IUserGroup::ID['JXL'] => 'JXL',
        IUserGroup::ID['RJJ'] => 'RJJ',
        IUserGroup::ID['JRL'] => 'JRL',
        IUserGroup::ID['QYJ'] => 'QYJ',
        IUserGroup::ID['TMZ'] => 'TMZ',
        IUserGroup::ID['SJZ'] => 'SJZ',
        IUserGroup::ID['YBJ'] => 'YBJ',
        IUserGroup::ID['KFQ'] => 'KFQ',
        IUserGroup::ID['QGZ'] => 'QGZ',
        IUserGroup::ID['SJJ'] => 'SJJ',
        IUserGroup::ID['SHCJ'] => 'SHCJ',
    );
}
