<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'QFGW' => 1,
        'QWWXB' => 2,
        'RMTZX' => 3,
        'SWJ' => 4,
        'ZJW' => 5,
        'WJW' => 6,
        'NW' => 7,
        'GZW' => 8,
        'KJJ' => 9,
        'GXJ' => 10,
        'GAFJ' => 11,
        'JCY' => 12,
        'FY' => 13,
        'CZJ' => 14,
        'SHUIWJ' => 15,
        'WLJ' => 16,
        'JRJ' => 17,
        'SCJGJ' => 18,
        'RSJ' => 19,
        'MZJ' => 20,
        'YGJ' => 21,
        'YJGLJ' => 22,
        'JYJ' => 23,
        'SFJ' => 24,
        'ZFB' => 25,
        'QWXCB' => 26,
        'XFBCZD' => 76,
        'BCZ' => 66,
        'YXFZ' => 70,
        'XDZ' => 71,
        'DZZZ' => 72,
        'SKZ' => 68,
        'XTTZ' => 73,
        'QGHZRZYJ' => 27,
        'STHJJ' => 36,
        'TJJ' => 33,
        'DAJ' => 32,
        'RFB' => 61,
        'CGW' => 30,
        'BMJ' => 97,
        'QSWJ' => 78,
        'QWTZB' => 98,
        'XCJ' => 93,
        'PDJ' => 57,
        'JXL' => 58,
        'RJJ' => 62,
        'JRL' => 63,
        'QYJ' => 64,
        'TMZ' => 65,
        'SJZ' => 67,
        'YBJ' => 60,
        'KFQ' => 90,
        'QGZ' => 69,
        'SJJ' => 38,
        'SHCJ' => 96
    );
}
